"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-Olas',
 'project_name': 'Pearl Marshal',
 'track': 'Autonolas Olas',
 'pitch': 'A marketplace-ready swarm coordinator that hires specialized workers, '
          'serves its own monitoring API, and records request counts toward '
          'monetization targets.',
 'idea_titles': ['Pearl-integrated Yield Ops Agent',
                 'Hire-and-Verify Execution Mesh',
                 'Monetized Lido Monitor'],
 'architecture_summary': 'The repo frames a marketplace agent that hires specialized '
                         'workers, serves its own monitoring API, and records request '
                         'counts toward monetization targets. Onchain coordination '
                         'data is separated from Python service adapters so live '
                         'mech-client or mech-server wiring can be dropped in later.',
 'overlap_targets': ['OpenServ',
                     'ERC-8004 Receipts',
                     'Lido Vault Monitor',
                     'Bankr Gateway',
                     'Uniswap Agentic Finance',
                     'Ampersend'],
 'primary_contract_name': 'PearlMarshalCoordinator',
 'primary_python_module': 'pearl_marshal',
 'category': 'orchestration',
 'daily_budget_usd': 114,
 'per_action_budget_usd': 28,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'problem_signal',
                       'description': 'Discovery inputs used to detect a real '
                                      'opportunity.'},
                      {'name': 'policy_envelope',
                       'description': 'Budget, caps, and cooldown policy state.'},
                      {'name': 'execution_bundle',
                       'description': 'Dry-run and live execution bundle metadata.'},
                      {'name': 'receipts',
                       'description': 'Submission notes and final verification '
                                      'digests.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for PearlMarshalCoordinator.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'pearl_marshal.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'Olas',
               'docs_url': 'https://docs.olas.network/',
               'env_vars': ['OLAS_API_KEY', 'OLAS_REQUEST_URL'],
               'endpoint_env': 'OLAS_REQUEST_URL',
               'action_kind': 'rest_json',
               'purpose': 'Hire and serve marketplace requests with receipts.'},
              {'name': 'OpenServ',
               'docs_url': 'https://docs.openserv.ai/',
               'env_vars': ['OPENSERV_API_KEY', 'OPENSERV_AGENT_URL'],
               'endpoint_env': 'OPENSERV_AGENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Dispatch jobs and expose swarm service endpoints.'},
              {'name': 'ERC-8004 Receipts',
               'docs_url': 'https://eips.ethereum.org/EIPS/eip-8004',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Anchor identity, task receipts, and reputation updates.'},
              {'name': 'Lido Vault Monitor',
               'docs_url': 'https://docs.lido.fi/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Monitor vault state and anchor alert digests.'},
              {'name': 'Bankr Gateway',
               'docs_url': 'https://bankr.bot/',
               'env_vars': ['BANKR_API_KEY',
                            'BANKR_CHAT_COMPLETIONS_URL',
                            'BANKR_MODEL'],
               'endpoint_env': 'BANKR_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Route inference through cost-aware model selection.'},
              {'name': 'Uniswap',
               'docs_url': 'https://developers.uniswap.org/',
               'env_vars': ['UNISWAP_API_KEY', 'UNISWAP_QUOTE_URL'],
               'endpoint_env': 'UNISWAP_QUOTE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Quote swaps and bounded liquidity moves.'},
              {'name': 'Ampersend',
               'docs_url': 'https://docs.ampersend.ai/',
               'env_vars': ['AMPERSEND_API_KEY', 'AMPERSEND_PAYMENT_URL'],
               'endpoint_env': 'AMPERSEND_PAYMENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Bundle payment and transport metadata for downstream '
                          'agents.'}],
 'actions': [{'id': 'olas_market_hire',
              'target': 'olas',
              'purpose': 'Use Olas for a bounded action in this repo.',
              'partner': 'Olas',
              'action_kind': 'rest_json',
              'max_amount_usd': 20,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call Olas only after a dry-run artifact exists.',
                        'Use https://docs.olas.network/ for credential setup.']},
             {'id': 'openserv_job_dispatch',
              'target': 'openserv',
              'purpose': 'Use OpenServ for a bounded action in this repo.',
              'partner': 'OpenServ',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 95,
              'sensitivity': 'medium',
              'notes': ['Call OpenServ only after a dry-run artifact exists.',
                        'Use https://docs.openserv.ai/ for credential setup.']},
             {'id': 'erc_8004_receipts_receipt_anchor',
              'target': 'erc_8004_receipts',
              'purpose': 'Use ERC-8004 Receipts for a bounded action in this repo.',
              'partner': 'ERC-8004 Receipts',
              'action_kind': 'contract_call',
              'max_amount_usd': 1,
              'priority': 90,
              'sensitivity': 'medium',
              'notes': ['Call ERC-8004 Receipts only after a dry-run artifact exists.',
                        'Use https://eips.ethereum.org/EIPS/eip-8004 for credential '
                        'setup.']},
             {'id': 'lido_vault_monitor_vault_alert',
              'target': 'lido_vault_monitor',
              'purpose': 'Use Lido Vault Monitor for a bounded action in this repo.',
              'partner': 'Lido Vault Monitor',
              'action_kind': 'contract_call',
              'max_amount_usd': 1,
              'priority': 85,
              'sensitivity': 'medium',
              'notes': ['Call Lido Vault Monitor only after a dry-run artifact exists.',
                        'Use https://docs.lido.fi/ for credential setup.']},
             {'id': 'bankr_gateway_compute_route',
              'target': 'bankr_gateway',
              'purpose': 'Use Bankr Gateway for a bounded action in this repo.',
              'partner': 'Bankr Gateway',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 80,
              'sensitivity': 'high',
              'notes': ['Call Bankr Gateway only after a dry-run artifact exists.',
                        'Use https://bankr.bot/ for credential setup.']},
             {'id': 'uniswap_quote_route',
              'target': 'uniswap',
              'purpose': 'Use Uniswap for a bounded action in this repo.',
              'partner': 'Uniswap',
              'action_kind': 'rest_json',
              'max_amount_usd': 220,
              'priority': 75,
              'sensitivity': 'medium',
              'notes': ['Call Uniswap only after a dry-run artifact exists.',
                        'Use https://developers.uniswap.org/ for credential setup.']},
             {'id': 'ampersend_settlement_bundle',
              'target': 'ampersend',
              'purpose': 'Use Ampersend for a bounded action in this repo.',
              'partner': 'Ampersend',
              'action_kind': 'rest_json',
              'max_amount_usd': 25,
              'priority': 70,
              'sensitivity': 'medium',
              'notes': ['Call Ampersend only after a dry-run artifact exists.',
                        'Use https://docs.ampersend.ai/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
